### ISSUE TITLE
When I try saving in the source Project I get exception 

### ISSUE THREAD

**Issue by Harinivenk** [lsgs/redcap-copy-data-on-save#1]
Hi , 

This is the first time i am trying to use this module . It is very much needed for my project

But I am not sure if i am wrong.. i get the following exception when i save in the source project 

The 'copy_data_on_save' module threw the following exception when calling the hook method 'redcap_save_record':

TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /home/ec2-user/project/redcap/modules/copy_data_on_save_v1.0.0/CopyDataOnSave.php:159
Stack trace:
#0 /home/ec2-user/project/redcap/modules/copy_data_on_save_v1.0.0/CopyDataOnSave.php(159): count('The following f...')
#1 /home/ec2-user/project/redcap/redcap_v11.4.0/ExternalModules/classes/ExternalModules.php(2809): MCRI\CopyDataOnSave\CopyDataOnSave->redcap_save_record('28', 'K202122413', 'maternal_admiss...', '58', '45', NULL, NULL, 1)
#2 /home/ec2-user/project/redcap/redcap_v11.4.0/ExternalModules/classes/ExternalModules.php(2937): ExternalModules\ExternalModules::startHook('copy_data_on_sa...', 'v1.0.0', Array)
#3 /home/ec2-user/project/redcap/redcap_v11.4.0/ExternalModules/classes/ExternalModules.php(2970): ExternalModules\ExternalModules::ExternalModules\{closure}('copy_data_on_sa...', 'v1.0.0')
#4 /home/ec2-user/project/redcap/redcap_v11.4.0/Classes/Hooks.php(42): ExternalModules\ExternalModules::callHook('save_record', Array)
#5 /home/ec2-user/project/redcap/redcap_v11.4.0/Classes/DataEntry.php(5416): Hooks::call('redcap_save_rec...', Array)
#6 /home/ec2-user/project/redcap/redcap_v11.4.0/DataEntry/index.php(249): DataEntry::saveRecord('K202122413', true, false, false, NULL, true, false)
#7 {main}

Can you please guide me if i am wrong

**Comment by lsgs** [comment]
I think this would have been a PHP8 issue @Harinivenk. It should not be a probleem in v1.1.0
