### ISSUE TITLE
Trigger condition prevents copying from repeating form

### ISSUE THREAD

**Issue by nb-tran** [lsgs/redcap-copy-data-on-save#12]
I encountered a weird issue with copying from a repeating form. Whenever I define a trigger condition the process would fail and nothing gets copied (even if the condition is met). However, when I remove the condition (ie. it always copies) it works again. Can someone confirm this behavior?

**Comment by lsgs** [comment]
Hello @nb-tran. That sounds very much like there is a syntax error with your logic, but I can't tell for sure without seeing the syntax you're trying to use (and possibly a project XML or data dictionary).

**Comment by YvesT73** [comment]
Hello @nb-tran @lsgs. This is likely indeed an incorrect specification of the logic. In case of a repeating form, add [current-instance] to the field. For example, instead of:
[confirm_for_blacklist(1)] = '1' 
use:
[confirm_for_blacklist(1)][current-instance] = '1'

**Comment by lsgs** [comment]
Thanks for chipping in @YvesT73. I'll close this in the absence of more detailed info.
