### ISSUE TITLE
Additional record created in source arm

### ISSUE THREAD

**Issue by whyaretheresomanylongs** [lsgs/redcap-copy-data-on-save#13]
I have a longitudinal project with multiple arms. On the first arm is where the main study data is recorded with a record per participant. There is a repeating form in this arm to record adverse events. When an adverse event is marked as "serious", we are using "copy data on save" to create a new record in arm 2, which just has a form to monitor the follow-up of the SAE. For example, in arm 1 participant "W010" has recorded a serious adverse event, this should trigger a new record in arm 2 called "W010_1" (whereby "_1", is the repeat instance of the AE form). This works in that "W010_1" is created in the destination arm 2, however the "W010_1" record is also getting created in arm 1, which is the source of the data.

**Comment by whyaretheresomanylongs** [comment]
Here is an image of the record being created in two arms:
![image](https://github.com/lsgs/redcap-copy-data-on-save/assets/35082700/f1cdf230-156e-41ee-954e-d31ce85ac62e)

**Comment by lsgs** [comment]
Thanks for the report @whyaretheresomanylongs. I'll contact you separately as I am struggling to replicate this in my v1.1.1 of the module. I'm wondering if there is something I'm doing differently in my project setup or module config...

**Comment by lsgs** [comment]
Problem should be fixed in version 1.2.0
