### ISSUE TITLE
Suggestion: Email notification on failure

### ISSUE THREAD

**Issue by ThomasVermes** [lsgs/redcap-copy-data-on-save#16]
![image](https://github.com/user-attachments/assets/39790503-3328-4087-adf4-4b8e3f1ebab5)
It would be nice if the an email could be put in the setting to be notified if there is some failure

**Comment by lsgs** [comment]
Look for this in version 1.4.0, which should be available from the official repo very soon @ThomasVermes. Thanks

![image](https://github.com/user-attachments/assets/479c77f2-1f19-455f-aeda-5e118f9d98e4)
