### ISSUE TITLE
File upload fields do not copy to destination

### ISSUE THREAD

**Issue by forestwolves** [lsgs/redcap-copy-data-on-save#2]
I use your module a lot for auto assigning data access groups and have recently started to use to copy data from one instrument to another and have come across a problem that when I try to copy a document from a file upload field to a file upload field in another instrument it does not copy across.

**Comment by lsgs** [comment]
I am glad you find the module useful @forestwolves. You're right - file fields are not currently supported for copying. That would be a worthwhile addition so I will leave this issue open. I should at least document the limitation.

**Comment by lsgs** [comment]
The facility for including files in the field data copied is included in v1.2.0
