### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by harpsicord86** [lsgs/redcap-copy-data-on-save#3]
Hi there,

My workplace currently uses this module in its REDCap installation and our IT department is looking to update its infrastructure to REDCap v13. However, I know that REDCap v13 uses PHP8 and so I wanted to ask if there is a plan in place to ensure that this module is PHP8 supported? Or is it already? Thanks

**Comment by lsgs** [comment]
Hello @harpsicord86. The module does work with PHP 8, well, to PHP 8.1, at least. I have not used 8.2 yet.

BTW, my understanding is that it is support for 8.2 that is new with REDCap v13.1.0. Also, support for PHP 7.2 is being dropped, but 7.3 and 7.4 will be supported for a little while yet.
