### ISSUE TITLE
New records created always in "Incomplete" state

### ISSUE THREAD

**Issue by nsonanh** [lsgs/redcap-copy-data-on-save#4]
Thank you for creating a very helpful module. Recently I need to use your module in a way that the created records won't be modified anymore. However all created records are in `Incomplete` state, which is a bit misleading for the user. Is there a way that we can set the status of those created records before they were created ?

**Comment by lsgs** [comment]
If you want to set a form status field in the destination project to "Complete" then map a field that will have the value '2' in the source project to be copied to it. It could be a form status field in the source, a calc field, a text field with @SETVALUE='2' - whatever.
