### ISSUE TITLE
Cannot copy data from source instrument if it not held within the first event

### ISSUE THREAD

**Issue by harpsicord86** [lsgs/redcap-copy-data-on-save#5]
Hi @lsgs,

I've noticed that if you want to copy data from source to destination and the source instrument is set within a different event other than the first then the copy does not work :-( is there a way around this at all (ideally NOT moving the instrument into the first event)

Thanks

**Comment by lsgs** [comment]
I have done some testing (with v1.1.0) and am not seeing that problem, @harpsicord86. You should find that that you can copy to and from any specified event. Can you check your project's Logging page? You should find a log event there whenever the trigger condition is met, and then another if the copy fails for some reason.

**Comment by harpsicord86** [comment]
Thanks for getting back to me @lsgs ... I've done has you've suggested, and I can only see a log event for my other instrument in the first event. The log is just showing that I've updated a record otherwise. Here are some screenshots of the settings and the logs for you to see:

![image](https://github.com/lsgs/redcap-copy-data-on-save/assets/12445814/b183ab93-8343-489a-aad4-bde063aa9e02)

![image](https://github.com/lsgs/redcap-copy-data-on-save/assets/12445814/57659f79-8504-412b-a558-7e5d5a1e6b5d)
![image](https://github.com/lsgs/redcap-copy-data-on-save/assets/12445814/afbd6ea8-b5ba-4d20-90b7-6026acf3b14b)

Hopefully you can see what I'm doing wrong.

**Comment by lsgs** [comment]
You have not set the event name for the destination event there @harpsicord86. That is required when you are copying to an event that is different to that where the copy gets triggered from.
