### ISSUE TITLE
citation file .cff

### ISSUE THREAD

**Issue by ThomasVermes** [lsgs/redcap-copy-data-on-save#9]
Dear Luke
what about to add a citation file (.cff)?
https://citation-file-format.github.io/#:~:text=cff%20files%20are%20plain%20text,to%20correctly%20cite%20their%20software.
https://redcap.vanderbilt.edu/community/post.php?id=118384

I would like to write a technical paper on a data collection project and I would like to cite your EM!

lg
Thomas

**Comment by lsgs** [comment]
I've not come across citation files before, but it sounds like a good idea. Does this work for you?
[CITATION.cff](https://github.com/lsgs/redcap-copy-data-on-save/blob/main/CITATION.cff)

Thanks for the thought @ThomasVermes! (And I have not forgotten the lookup by 2nd identifier enhancement, BTW! I want to get that implemented soon...)

**Comment by ThomasVermes** [comment]
That's great!
I'm using Zotero as reference managment tool and it recognise well the file. Here the result with APA7 style:

![image](https://github.com/lsgs/redcap-copy-data-on-save/assets/75424115/2669361d-8eb2-425c-9561-e34076dbd664)

Hope you don't mind if I'll open the same issue by other EMs in case I'll cite them =)
thanks a lot
Thomas
